# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

def find_arg(args = [])
  args.each do |arg|
    ARGV.each do |a|
      if a == arg || a.match("^#{arg}=")
        index = ARGV.index(a)
        ARGV.slice!(index)

        return arg if a == arg

        if arg.match("^--")
          split = a.split '='
          return a.split("=")[1] if split.length == 2
          return arg
        end
      end
    end
  end
  nil
end

@ml_version = find_arg(["-v","--ml-version"]) || "7"
@nr_hosts = (find_arg(["-n","--nr-hosts"]) || "3").to_i

def get_vm_name(i)
  File.basename(Dir.getwd) + "-v" + @ml_version  + "-ml" + i.to_s
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    
    mastername = get_vm_name(1)
  
    config.hostmanager.enabled = false
    config.hostmanager.manage_host = true
    config.hostmanager.include_offline = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.ip_resolver = proc do |machine|
        result = ""
        machine.communicate.execute("ifconfig eth1") do |type, data|
          result << data if type == :stdout
        end
        (ip = /^\s*inet .*?(\d+\.\d+\.\d+\.\d+)\s+/.match(result)) && ip[1]
    end
    
    config.vm.define mastername do |master|
        master.vm.box = "chef/centos-6.5"
        master.vm.provider "virtualbox" do |v|
            v.name = mastername
            v.memory = 2048
            v.cpus = 2
        end
        master.vm.hostname = mastername
        master.vm.network "public_network", bridge: 'en0: Wi-Fi (AirPort)'
        master.vm.synced_folder "/opt/vagrant", "/opt/vagrant"
        master.vm.synced_folder "/space/software", "/space/software"
        
        master.vm.provision :hostmanager
        master.vm.provision :shell, :path => "/opt/vagrant/bootstrap-centos-master.sh", :args => ["-v", "#{@ml_version}", File.basename(Dir.getwd)]
    end
    
    if @nr_hosts > 1
        (2..@nr_hosts).each do |i|
          hostname = get_vm_name(i)
          config.vm.define hostname do |data|
                data.vm.box = "chef/centos-6.5"
                data.vm.provider "virtualbox" do |v|
                    v.name = hostname
                    v.memory = 2048
                    v.cpus = 2
                end
                data.vm.hostname = hostname
                data.vm.network "public_network", bridge: 'en0: Wi-Fi (AirPort)'
                data.vm.synced_folder "/opt/vagrant", "/opt/vagrant"
                data.vm.synced_folder "/space/software", "/space/software"
                
                data.vm.provision :hostmanager
                data.vm.provision :shell, :path => "/opt/vagrant/bootstrap-centos-extra.sh", :args => ["-v", "#{@ml_version}", mastername, "localhost"]
            end
        end
    end
    
end
